### ISSUE TITLE
Gameplay: Improve the current gameplay

### ISSUE THREAD

**Issue by RudraNilBasu** [BytesClub/Tic_Tac_Toe#21]
The gameplay should be something like this:

**Start Page**:

```
Welcome to Tic Tac Toe
Made by: Bytes Club

* your-name <email id>
* ....

Loading.... Please wait
```

**Next page** : 

```

1 | 2 | 3
----------
4 | 5 | 6
----------
7 | 8 | 9

For player X: 
Enter position: <position>

/* Display the board updated*/
For player O: 
Enter position: <position>
....
```

**Comment by Amitava123** [comment]
ok what does your name and email id specifies here? will that be of player?

**Comment by 0xTheProDev** [comment]
No the name of the contributor of the projects and their respective email address!
You will be given a file containing both information.

**Comment by RudraNilBasu** [comment]
@Amitava123 For the credits section, create a separate file for credits, with methods to display
the name of the contributors of the projects. Then call the function from greet()

**Comment by Amitava123** [comment]
ok got it

**Comment by 0xTheProDev** [comment]
@RudraNilBasu  I think this issue can be separated into two part:
1. Display contributor list in welcome message.
2. Show position number instead of NULL character in Board.
