### ISSUE TITLE
make main gives error

### ISSUE THREAD

**Issue by amitiwary999** [BytesClub/Tic_Tac_Toe#36]
### Steps to reproduce
1.
2.
3.

### Actual behavior
error  : make: *** No rule to make target `main'.  Stop.

### Environment configuration
**Operating system**:ubuntu

**Compiler**:gcc

**Compiler version**:4.8.4

**Comment by RudraNilBasu** [comment]
The makefile is updated as of now and the README is not yet updated, but simply a make command will
do here:

```
make
```
