### ISSUE TITLE
Bug: Infinite loop on entering non-integers.

### ISSUE THREAD

**Issue by Sameem25** [BytesClub/Tic_Tac_Toe#38]
### Steps to reproduce
1. compile and run it correctly.
2. wait till loading completes.
3. enter a character but not the position number.

![capture1](https://cloud.githubusercontent.com/assets/25945349/26031884/45b694de-3838-11e7-919a-f19f9fb4135f.PNG)

### Expected behavior
Probably a single line signal to mention incorrect input.

### Actual behavior
Infinite loop
![capture2](https://cloud.githubusercontent.com/assets/25945349/26031881/36862876-3838-11e7-8b79-e3fa7f24d2a7.PNG)

### Environment configuration
**Operating system**: Ubuntu 16.04

**Comment by RudraNilBasu** [comment]
@Sameem17 thank you for the issue, you can start working on it. Before you do, have a 
read at these [guidelines](https://bytesclub.github.io/contributing/#tips-for-contribution)
