### ISSUE TITLE
Human-Computer Interaction

### ISSUE THREAD

**Issue by 0xTheProDev** [BytesClub/Tic_Tac_Toe#39]
* Add Feature for playing against a computer BOT.
* BOT must select move by a random selection.

**Comment by satyamvats5** [comment]
The move made by the BOT will be random???

**Comment by 0xTheProDev** [comment]
For now, yes!

**Comment by satyamvats5** [comment]
There will be two options available for the user either two play with another user or to play with BOT???

**Comment by 0xTheProDev** [comment]
Yes. It will be selected before the board formation!
