### ISSUE TITLE
Gameplay: Segmentation fault on entering character as position

### ISSUE THREAD

**Issue by RudraNilBasu** [BytesClub/Tic_Tac_Toe#43]
### Steps to reproduce
1. `./play 3`
2. 
```
    For Player('X'):
    Enter Position: x
```

### Expected behavior
```
Error: Invalid position.
```

### Actual behavior
```
play: src/main.c:37: main: Assertion `scanf("%d", &pos) == 1' failed.
[1]    8698 abort (core dumped)  ./play 3
```

### Environment configuration
**Operating system**: Testen on Ubuntu

**Compiler**: gcc

**Compiler version**: 5.4.0

**Comment by satyamvats5** [comment]
Game will exit on entering a character , or will it give a warning and asks the user to enter position again?

**Comment by RudraNilBasu** [comment]
@satyamvats5 It should provide an error and ask us to re-enter the position.
