### ISSUE TITLE
make command not working

### ISSUE THREAD

**Issue by sammy00747** [BytesClub/Tic_Tac_Toe#49]
### Steps to reproduce
1. ./bin/play
2.
3.

### Expected behavior
Usage: ./bin/play n
n: Dimension of the Board

### Actual behavior
./bin/play: No such file or directory

### Environment configuration
**Operating system**: Ubuntu 16.04.4

![capture](https://user-images.githubusercontent.com/25882331/28272759-16558658-6b2a-11e7-8ac0-4e0c6d800231.PNG)

**Compiler**: gcc

**Compiler version**: 5.4.0

**Comment by RudraNilBasu** [comment]
Remove the `test.c` file and try `make` again
